baseURL: "https://spacestation14.com/"
languageCode: "en-us"
title: "Space Station 14"
ignoreFiles: ["\\.ts$", "tsconfig.json$"]
mainSections: ["post"]

params:
  mainFeedSections: ["post", "updates"]

# PYGMENTS (Syntax Highlighting) settings!
# I couldn't get Chroma to parse C# at all.
PygmentsUseClassic: true
PygmentsCodeFences: true
PygmentsUseClasses: true

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true

module:
  mounts:
  - source: "static"
    target: "static"
  - source: "assets"
    target: "assets"
  - source: "node_modules/@fortawesome/fontawesome-free/webfonts"
    target: "static/fonts/fontawesome"
  - source: "node_modules/@fortawesome/fontawesome-free/scss"
    target: "assets/scss/fontawesome"
  - source: "node_modules/bootstrap/scss"
    target: "assets/scss/bootstrap"
  - source: "node_modules/petite-vue/dist/"
    target: "static/js/vue/"
    includeFiles: "petite-vue.es.js"
